require 'gitter/filters/filter'
require 'gitter/filters/abstract_filter_spec'
require 'gitter/filters/block_filter_spec'
require 'gitter/filters/select_filter_spec'
require 'gitter/filters/column_filter_spec'
